name: public_ipeds
config-version: 2

version: '1.0.0'
profile: public_ipeds

macro-paths: ["macros"]
model-paths: ["models"]
seed-paths: ["seeds"]

models:
  public_ipeds:
    staging:
      +schema: stage
      +materialized: view

    intermediate:
      +materialized: ephemeral

    marts:
      +schema: marts
      +materialized: table
      stars: 
        +schema: stars
        +materialized: view

seeds:
  public_ipeds:
    +schema: raw