repos:
  - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: v2.0.8
    hooks:
      - id: check-script-semicolon
        files: ^dbt/models/.*\.sql$
        args: ["--manifest", "dbt/target/manifest.json"]
      - id: check-script-has-no-table-name
        files: ^dbt/models/.*\.sql$
        args: ["--manifest", "dbt/target/manifest.json"]
      - id: check-script-ref-and-source
        files: ^dbt/models/.*\.sql$
        args: ["--manifest", "dbt/target/manifest.json"]
      - id: check-model-has-properties-file
        files: ^dbt/models/.*\.sql$
        args: ["--manifest", "dbt/target/manifest.json"]
      - id: check-source-has-all-columns
        name: Source check columns
        files: ^dbt/models/.*\.sql$
        args: ["--manifest", "dbt/target/manifest.json",
               "--catalog", "dbt/target/catalog.json"]
      - id: check-model-has-all-columns
        name: Model check columns
        files: ^dbt/models/.*\.sql$
        args: ["--manifest", "dbt/target/manifest.json",
               "--catalog", "dbt/target/catalog.json"]