with source as (
        select * from {{ source('raw', 'c2024_a') }}
  ),
  renamed as (
      select
        2024 as survey_year,
        unitid as institution_id,
        cipcode as cip_code,
        majornum as major_number,
        awlevel as award_level,
        xctotalt as provisional_total_completions,
        ctotalt as total_completions,
        xctotalm as provisional_male_completions,
        ctotalm as male_completions,
        xctotalw as provisional_female_completions,
        ctotalw as female_completions,
        xcaiant as provisional_aian_total_completions,
        caiant as aian_total_completions,
        xcaianm as provisional_aian_male_completions,
        caianm as aian_male_completions,
        xcaianw as provisional_aian_female_completions,
        caianw as aian_female_completions,
        xcasiat as provisional_asian_total_completions,
        casiat as asian_total_completions,
        xcasiam as provisional_asian_male_completions,
        casiam as asian_male_completions,
        xcasiaw as provisional_asian_female_completions,
        casiaw as asian_female_completions,
        xcbkaat as provisional_black_total_completions,
        cbkaat as black_total_completions,
        xcbkaam as provisional_black_male_completions,
        cbkaam as black_male_completions,
        xcbkaaw as provisional_black_female_completions,
        cbkaaw as black_female_completions,
        xchispt as provisional_hispanic_total_completions,
        chispt as hispanic_total_completions,
        xchispm as provisional_hispanic_male_completions,
        chispm as hispanic_male_completions,
        xchispw as provisional_hispanic_female_completions,
        chispw as hispanic_female_completions,
        xcnhpit as provisional_nhpi_total_completions,
        cnhpit as nhpi_total_completions,
        xcnhpim as provisional_nhpi_male_completions,
        cnhpim as nhpi_male_completions,
        xcnhpiw as provisional_nhpi_female_completions,
        cnhpiw as nhpi_female_completions,
        xcwhitt as provisional_white_total_completions,
        cwhitt as white_total_completions,
        xcwhitm as provisional_white_male_completions,
        cwhitm as white_male_completions,
        xcwhitw as provisional_white_female_completions,
        cwhitw as white_female_completions,
        xc2mort as provisional_two_or_more_races_total_completions,
        c2mort as two_or_more_races_total_completions,
        xc2morm as provisional_two_or_more_races_male_completions,
        c2morm as two_or_more_races_male_completions,
        xc2morw as provisional_two_or_more_races_female_completions,
        c2morw as two_or_more_races_female_completions,
        xcunknt as provisional_unknown_race_total_completions,
        cunknt as unknown_race_total_completions,
        xcunknm as provisional_unknown_race_male_completions,
        cunknm as unknown_race_male_completions,
        xcunknw as provisional_unknown_race_female_completions,
        cunknw as unknown_race_female_completions,
        xcnralt as provisional_nonresident_alien_total_completions,
        cnralt as nonresident_alien_total_completions,
        xcnralm as provisional_nonresident_alien_male_completions,
        cnralm as nonresident_alien_male_completions,
        xcnralw as provisional_nonresident_alien_female_completions,
        cnralw as nonresident_alien_female_completions

      from source
  )
  select * from renamed
    